My Project: AnalogClockViewHandler
AnalogClockViewHandler
#include "AnalogClockViewHandler.h"
Public Member Functions
AnalogClockViewHandler (TimeHandler *ptr, const int minL_pin, const int minR_pin, const int secL_pin, const int secR_pin)
virtual ~AnalogClockViewHandler (void)
virtual const char * getClassName (void)
void resetHands ()
virtual void updateTime (Timestamp &timestamp)
Public Member Functions inherited from TimeHandler
TimeHandler (TimeHandler *ptr=nullptr)
virtual ~TimeHandler (void)
virtual void bypass (bool bypassModule)
virtual const char * getClassName (void)=0
virtual bool isValidTime (void)
virtual void setValidTime (bool validFlagg)
virtual void updateTime (Timestamp &timestamp)
Private Member Functions
void doAction (void(*fun)(void))
void moveHands (void)
void moveMinuteHandStep1 (void)
void moveMinuteHandStep2 (void)
void moveOnlyMinuteHand (void)
void moveOnlySecondHand (void)
void moveSecondHandStep1 (void)
void moveSecondHandStep2 (void)
Private Attributes
MyTime clockTimePresented
const int minL_pin
const int minR_pin
const int secL_pin
const int secR_pin
Additional Inherited Members
Protected Attributes inherited from TimeHandler
bool bypassModule
TimeHandler * ptr
bool validTime
Detailed Description
Constructor & Destructor Documentation
AnalogClockViewHandler()
AnalogClockViewHandler (TimeHandler * ptr, const int minL_pin, const int minR_pin, const int secL_pin, const int secR_pin)
  :TimeHandler( ptr), minL_pin( minL_pin), minR_pin( minR_pin), secL_pin( secL_pin), secR_pin( secR_pin)
{
  pinMode( minL_pin, OUTPUT);     pinMode( minR_pin, OUTPUT);
  digitalWrite( minL_pin, HIGH);   digitalWrite( minR_pin, HIGH);
  pinMode( secL_pin, OUTPUT);     pinMode( secR_pin, OUTPUT);
  digitalWrite( secL_pin, HIGH);   digitalWrite( secR_pin, HIGH);
};
References minL_pin, minR_pin, secL_pin, and secR_pin.
~AnalogClockViewHandler()
~AnalogClockViewHandler (void) virtual
{};
Member Function Documentation
doAction()
void doAction (void(*)(void) fun) private
{
  (*fun)();
}
getClassName()
const char * getClassName (void) virtual
Implements TimeHandler.
{
  return("AnalogClockViewHandler");
}
moveHands()
void moveHands (void) private
{
  static bool wasFirstSecondInSync= false;
  if( !isValidTime())
  {
    wasFirstSecondInSync= false;
    Serial.println("Invalid time\n");
  }
  if( isValidTime() &&( clockTimePresented.getSecond() ==1))
  {
    wasFirstSecondInSync= true;
    Serial.println("VALID time\n");
  }
  if( wasFirstSecondInSync&& isValidTime())
  {
    if( clockTimePresented.getSecond() ==1)
    {
      moveMinuteHandStep1();
    }
    moveSecondHandStep1();
  }
  Timer t( PULS_LENGTH);
  t.delay();
  if( wasFirstSecondInSync&& isValidTime())
  {
    moveMinuteHandStep2();
    moveSecondHandStep2();
    // call lambda function
    /*
    doAction( []() {
      Serial.println( "moveOnlyMinuteHand");
      AnalogClockViewHandler::moveOnlyMinuteHand( 4, 5);
    });
    */
  }
  clockTimePresented++;
}
References clockTimePresented, Timer::delay(), MyTime::getSecond(), TimeHandler::isValidTime(), moveMinuteHandStep1(), moveMinuteHandStep2(), moveSecondHandStep1(), moveSecondHandStep2(), and PULS_LENGTH.
Referenced by updateTime().
moveMinuteHandStep1()
void moveMinuteHandStep1 (void) private
{
  static bool  tick= 0;
  if( tick)
  {
    digitalWrite( minL_pin, LOW);  digitalWrite( minR_pin, HIGH);
    tick= 0;
  }
  else
  {
    digitalWrite( minL_pin, HIGH);  digitalWrite( minR_pin, LOW);
    tick= 1;
  }
}
References minL_pin, and minR_pin.
Referenced by moveHands(), and moveOnlyMinuteHand().
moveMinuteHandStep2()
void moveMinuteHandStep2 (void) private
{
  digitalWrite( minL_pin, HIGH);  digitalWrite( minR_pin, HIGH);
}
References minL_pin, and minR_pin.
Referenced by moveHands(), and moveOnlyMinuteHand().
moveOnlyMinuteHand()
void moveOnlyMinuteHand (void) private
{
  moveMinuteHandStep1();
  Timer t( PULS_LENGTH);
  t.delay();
  moveMinuteHandStep2();
}
References Timer::delay(), moveMinuteHandStep1(), moveMinuteHandStep2(), and PULS_LENGTH.
moveOnlySecondHand()
void moveOnlySecondHand (void) private
{
  moveSecondHandStep1();
  Timer t( PULS_LENGTH);
  t.delay();
  moveSecondHandStep2();
}
References Timer::delay(), moveSecondHandStep1(), moveSecondHandStep2(), and PULS_LENGTH.
moveSecondHandStep1()
void moveSecondHandStep1 (void) private
{
  static bool  tick= 0;
  if( tick)
  {
    digitalWrite( secL_pin, LOW);  digitalWrite( secR_pin, HIGH);
    tick= 0;
  }
  else
  {
    digitalWrite( secL_pin, HIGH);  digitalWrite( secR_pin, LOW);
    tick= 1;
  }
}
References secL_pin, and secR_pin.
Referenced by moveHands(), and moveOnlySecondHand().
moveSecondHandStep2()
void moveSecondHandStep2 (void) private
{
  digitalWrite( secL_pin, HIGH);  digitalWrite( secR_pin, HIGH);
}
References secL_pin, and secR_pin.
Referenced by moveHands(), and moveOnlySecondHand().
resetHands()
void resetHands ()
{
/*
  for(;;)
  {
    clockTime++;
    moveOnlySecondHand();
    char timeStrBuffer[ MyTime::getStringBufferSize()];
    Serial.println( clockTime.toString( timeStrBuffer));
  }
*/
}
updateTime()
void updateTime (Timestamp & timestamp) virtual
Reimplemented from TimeHandler.
{
  MyTime    requiredTime;
  requiredTime= timestamp.getTime();
  requiredTime.setHour( requiredTime.getHour() % 12);  // analog clock has 12 hours
/*
  char timeStrBuffer2[ MyTime::getStringBufferSize()];
  Serial.printf( "requiredTime %s  | ",requiredTime.toString( timeStrBuffer2));
  char timeStrBuffer3[ MyTime::getStringBufferSize()];
  Serial.printf( "clockTimePresented %s  | ",clockTimePresented.toString( timeStrBuffer3));
  uint16_t   tdiff;
  tdiff= abs( requiredTime.getInSeconds()-  clockTimePresented.getInSeconds()) %(3600*12);
  Serial.printf( "Diff Time in secs %d\n",tdiff);
*/
  static bool flaggStart= false;
  if( timestamp.getTime().getSecond() ==0)
  {
    flaggStart = true;
  }
  if( flaggStart)
  {
    moveHands();
  }
  TimeHandler::updateTime( timestamp);
}
References MyTime::getHour(), MyTime::getSecond(), Timestamp::getTime(), moveHands(), MyTime::setHour(), and TimeHandler::updateTime().
Member Data Documentation
clockTimePresented
MyTime clockTimePresented private
Referenced by moveHands().
minL_pin
const int minL_pin private
Referenced by AnalogClockViewHandler(), moveMinuteHandStep1(), and moveMinuteHandStep2().
minR_pin
const int minR_pin private
Referenced by AnalogClockViewHandler(), moveMinuteHandStep1(), and moveMinuteHandStep2().
secL_pin
const int secL_pin private
Referenced by AnalogClockViewHandler(), moveSecondHandStep1(), and moveSecondHandStep2().
secR_pin
const int secR_pin private
Referenced by AnalogClockViewHandler(), moveSecondHandStep1(), and moveSecondHandStep2().
The documentation for this class was generated from the following files:
AnalogClockViewHandler.h
AnalogClockViewHandler.cpp