My Project: TimeSunriseSunsetHandler
TimeSunriseSunsetHandler
#include "TimeSunriseSunsetHandler.h"
Public Member Functions
TimeSunriseSunsetHandler (TimeHandler *ptr, double longitude, double latitude, MyTime &sunrise, MyTime &sunset)
virtual ~TimeSunriseSunsetHandler (void)
virtual const char * getClassName (void)
virtual void updateTime (Timestamp &timestamp)
Public Member Functions inherited from TimeHandler
TimeHandler (TimeHandler *ptr=nullptr)
virtual ~TimeHandler (void)
virtual void bypass (bool bypassModule)
virtual const char * getClassName (void)=0
virtual bool isValidTime (void)
virtual void setValidTime (bool validFlagg)
virtual void updateTime (Timestamp &timestamp)
Private Member Functions
long modd (double a, double b)
Private Attributes
double latitude
double longitude
MyTime & sunriseTime
MyTime & sunsetTime
Additional Inherited Members
Protected Attributes inherited from TimeHandler
bool bypassModule
TimeHandler * ptr
bool validTime
Detailed Description
Constructor & Destructor Documentation
TimeSunriseSunsetHandler()
TimeSunriseSunsetHandler (TimeHandler * ptr, double longitude, double latitude, MyTime & sunrise, MyTime & sunset)
:TimeHandler(ptr),longitude(longitude), latitude(latitude), sunriseTime(sunrise), sunsetTime(sunset)
{};
~TimeSunriseSunsetHandler()
~TimeSunriseSunsetHandler (void) virtual
{};
Member Function Documentation
getClassName()
const char * getClassName (void) virtual
Implements TimeHandler.
{
  return("TimeSunriseSunsetHandler");
}
modd()
long modd (double a, double b) private
{
  return((a-long(a))*b);
}
Referenced by updateTime().
updateTime()
void updateTime (Timestamp & timestamp) virtual
Reimplemented from TimeHandler.
{
  static uint8_t  lastday= 0;
  MyDate  date= timestamp.getDate();
  if( date.getDay() != lastday)
  {
    lastday= date.getDay();
    uint8_t day=   date.getDay();
    uint8_t month= date.getMonth();
    uint16_t year= date.getYear();
    double E6= ( month<=2)? ( month+12) :month;
    double E7= ( month<=2)? ( year-1): year;
    double L6 = 2-int(year/100)+int(year/400);
    double L7 = int(365.25*(E7+4716))+int(30.6001*(E6+1))+day+L6-1524.5;
    double M3 = (L7-2451545)/36525;
    double M4 = 280.46646 +36000.76983*M3+0.0003032*M3*M3;
    double M5 = 357.52911 +35999.05029*M3-0.0001537*M3*M3;
    double O5=  modd( (M5/360), 360) *GradToRad;
    double O4 = modd( (M4/360), 360);
    double M6 = (1.914602-0.004817*M3-0.000014*M3*M3)*sin(  O5);
    double M7 = (0.019993-0.000101*M3               )*sin(2*O5);
    double M8 =  0.000289                            *sin(3*O5);
    double M9 =  M6+M7+M8;
    double N7 = 125.04-1934.136*M3;
    double N9 = (N7 <0)? ( N7+360): N7;
    double M11 = 23.43930278-0.0130042*M3-0.000000163*M3*M3;
    double N10 = O4 +M9 -0.00569 -0.00478*sin(N9*GradToRad);
    double N11 = asin( sin( M11*GradToRad)*sin(N10*GradToRad));
    double N16 = -0.01483-sin( N11)*sin( latitude*GradToRad);
    double O16 =          cos( N11)*cos( latitude*GradToRad);
    double Z=    13-longitude/15+ (7.7*sin((O4+78)*GradToRad)-9.5*sin(2*O4*GradToRad))/60;
    double P15 = ( acos(N16/O16)*57.29577951)/15;
    double P17 = Z-P15; //- godzina wschodu Słońca
    double Q17 = Z+P15; //- godzina zachodu Słońca
    this->sunriseTime.setHour( (uint8_t)P17);
    this->sunriseTime.setMinute( (uint8_t) modd( P17, 60));
    this->sunriseTime.setSecond( (uint8_t) modd( P17, 3600)/10);
    this->sunsetTime.setHour( (uint8_t)Q17);
    this->sunsetTime.setMinute( (uint8_t)modd( Q17, 60));
    this->sunsetTime.setSecond( (uint8_t) modd( Q17, 3600)/10);
    char timeStrBuffer[ MyTime::getStringBufferSize()];
    Serial.printf("Wsch: %s  ",    this->sunriseTime.toString( timeStrBuffer));
    Serial.printf("/  Zach: %s\n", this->sunsetTime.toString( timeStrBuffer));
  }
  TimeHandler::updateTime( timestamp);
}
References Timestamp::getDate(), MyDate::getDay(), MyDate::getMonth(), MyTime::getStringBufferSize(), MyDate::getYear(), GradToRad, latitude, longitude, modd(), MyTime::setHour(), MyTime::setMinute(), MyTime::setSecond(), sunriseTime, sunsetTime, MyTime::toString(), and TimeHandler::updateTime().
Member Data Documentation
latitude
double latitude private
Referenced by updateTime().
longitude
double longitude private
Referenced by updateTime().
sunriseTime
MyTime& sunriseTime private
Referenced by updateTime().
sunsetTime
MyTime& sunsetTime private
Referenced by updateTime().
The documentation for this class was generated from the following files:
TimeSunriseSunsetHandler.h
TimeSunriseSunsetHandler.cpp