My Project: MyTime
MyTime
#include "MyTime.h"
Public Member Functions
MyTime (const MyTime &time)
MyTime (uint8_t hour, uint8_t minute, uint8_t second)
MyTime (void)
~MyTime (void)
uint8_t getHour (void) const
uint16_t getInSeconds (void)
uint8_t getMinute (void) const
uint8_t getSecond (void) const
void hourDec (void)
void hourInc (void)
void minuteDec (void)
void minuteInc (void)
MyTime operator++ (int)
MyTime & operator++ (void)
MyTime & operator= (const MyTime &time)
void secondDec (void)
void secondInc (void)
void setHour (uint8_t day)
void setInSeconds (uint16_t timeInSecs)
void setMinute (uint8_t minute)
void setSecond (uint8_t second)
char * toString (char *Stringbuffer)
Static Public Member Functions
static size_t getStringBufferSize (void)
static const char * getStringFormat (void)
static bool isValidHour (uint8_t hour)
static bool isValidMinute (uint8_t minute)
static bool isValidSecond (uint8_t second)
Private Attributes
uint8_t hour
uint8_t minute
uint8_t second
Detailed Description
Constructor & Destructor Documentation
MyTime() [1/3]
MyTime (void)
:hour(0), minute(0), second(0) {}
MyTime() [2/3]
MyTime (uint8_t hour, uint8_t minute, uint8_t second)
:hour(hour), minute(minute), second(second) {}
MyTime() [3/3]
MyTime (const MyTime & time)
:hour(time.hour), minute(time.minute), second(time.second) {}
~MyTime()
~MyTime (void)
{}
Member Function Documentation
getHour()
uint8_t getHour (void) const
{
  return( hour);
}
References hour.
Referenced by getInSeconds(), Timestamp::setTime(), and AnalogClockViewHandler::updateTime().
getInSeconds()
uint16_t getInSeconds (void)
{
  return( getHour()* 3600 + getMinute()*60 +getSecond());
}
References getHour(), getMinute(), and getSecond().
getMinute()
uint8_t getMinute (void) const
{
  return( minute);
}
References minute.
Referenced by getInSeconds(), and Timestamp::setTime().
getSecond()
uint8_t getSecond (void) const
{
  return( second);
}
References second.
Referenced by getInSeconds(), AnalogClockViewHandler::moveHands(), Timestamp::setTime(), and AnalogClockViewHandler::updateTime().
getStringBufferSize()
size_t getStringBufferSize (void) static
{
  return( strlen( MyTime::getStringFormat())+1);
}
References getStringFormat().
Referenced by Timestamp::toString(), LEDClockViewHandler::updateTime(), NTPWiFiTimeHandler::updateTime(), and TimeSunriseSunsetHandler::updateTime().
getStringFormat()
const char * getStringFormat (void) static
{
  return( "%02d:%02d:%02d");
}
Referenced by getStringBufferSize(), Timestamp::getStringBufferSize(), and toString().
hourDec()
void hourDec (void)
{
  hour =( hour> 0)? hour-1:23;
}
References hour.
Referenced by SystemTimeHandler::adjust().
hourInc()
void hourInc (void)
{
  hour =( hour< 24)? hour+1:0;
}
References hour.
Referenced by SystemTimeHandler::adjust().
isValidHour()
bool isValidHour (uint8_t hour) static
{
  return( hour< 24);
}
References hour.
Referenced by operator++().
isValidMinute()
bool isValidMinute (uint8_t minute) static
{
  return( minute< 60);
}
References minute.
Referenced by operator++().
isValidSecond()
bool isValidSecond (uint8_t second) static
{
  return( second< 60);
}
References second.
Referenced by operator++().
minuteDec()
void minuteDec (void)
{
  minute =( minute> 0)? minute-1:59;
}
References minute.
Referenced by SystemTimeHandler::adjust().
minuteInc()
void minuteInc (void)
{
  minute =( minute< 60)? minute+1:0;
}
References minute.
Referenced by SystemTimeHandler::adjust().
operator++() [1/2]
MyTime operator++ (int)
{
    ++( *this);
    return( *this);
}
operator++() [2/2]
MyTime & operator++ (void)
{
    second++;
    if( !isValidSecond( second))
    {
       second=0;
       minute++;
       if( !isValidMinute( minute))
       {
          minute=0;
          hour++;
          if( !isValidHour( hour))
          {
            hour=0;
          }
       }
    }
    return( *this);
}
References hour, isValidHour(), isValidMinute(), isValidSecond(), minute, and second.
operator=()
MyTime & operator= (const MyTime & time)
{
    if( &time != this )
    {
        hour=   time.hour;
        minute= time.minute;
        second= time.second;
    }
    return( *this);
}
References hour, minute, and second.
secondDec()
void secondDec (void)
{
  second =( second> 0)? second-1:59;
}
References second.
Referenced by SystemTimeHandler::adjust().
secondInc()
void secondInc (void)
{
  second =( second< 60)? second+1:0;
}
References second.
Referenced by SystemTimeHandler::adjust().
setHour()
void setHour (uint8_t day)
{
  this->hour= hour;
}
References hour.
Referenced by Timestamp::getTime(), setInSeconds(), AnalogClockViewHandler::updateTime(), and TimeSunriseSunsetHandler::updateTime().
setInSeconds()
void setInSeconds (uint16_t timeInSecs)
{
  uint16_t tdiff= timeInSecs;
  setHour(   ( uint8_t)(tdiff / 3600));  tdiff %= 3600;
  setMinute( ( uint8_t)(tdiff /   60));
  setSecond(    ( uint8_t)(tdiff %   60));
}
References setHour(), setMinute(), and setSecond().
setMinute()
void setMinute (uint8_t minute)
{
  this->minute= minute;
}
References minute.
Referenced by Timestamp::getTime(), setInSeconds(), and TimeSunriseSunsetHandler::updateTime().
setSecond()
void setSecond (uint8_t second)
{
  this->second= second;
}
References second.
Referenced by Timestamp::getTime(), setInSeconds(), and TimeSunriseSunsetHandler::updateTime().
toString()
char * toString (char * Stringbuffer)
{
  sprintf( ptr, MyTime::getStringFormat(), hour, minute, second);
  return( ptr);
}
References getStringFormat(), hour, minute, and second.
Referenced by Timestamp::toString(), LEDClockViewHandler::updateTime(), NTPWiFiTimeHandler::updateTime(), OLEDDisplayClockViewHandler::updateTime(), and TimeSunriseSunsetHandler::updateTime().
Member Data Documentation
hour
uint8_t hour private
Referenced by getHour(), hourDec(), hourInc(), isValidHour(), operator++(), operator=(), setHour(), and toString().
minute
uint8_t minute private
Referenced by getMinute(), isValidMinute(), minuteDec(), minuteInc(), operator++(), operator=(), setMinute(), and toString().
second
uint8_t second private
Referenced by getSecond(), isValidSecond(), operator++(), operator=(), secondDec(), secondInc(), setSecond(), and toString().
The documentation for this class was generated from the following files:
MyTime.h
MyTime.cpp