My Project: ConsoleViewHandler
ConsoleViewHandler
#include "ConsoleViewHandler.h"
Public Member Functions
ConsoleViewHandler (TimeHandler *ptr=nullptr)
virtual ~ConsoleViewHandler (void)
virtual const char * getClassName (void)
virtual void updateTime (Timestamp &timestamp)
Public Member Functions inherited from TimeHandler
TimeHandler (TimeHandler *ptr=nullptr)
virtual ~TimeHandler (void)
virtual void bypass (bool bypassModule)
virtual const char * getClassName (void)=0
virtual bool isValidTime (void)
virtual void setValidTime (bool validFlagg)
virtual void updateTime (Timestamp &timestamp)
Private Attributes
Timestamp lastTimestamp
Additional Inherited Members
Protected Attributes inherited from TimeHandler
bool bypassModule
TimeHandler * ptr
bool validTime
Detailed Description
Constructor & Destructor Documentation
ConsoleViewHandler()
ConsoleViewHandler (TimeHandler * ptr = nullptr)
:TimeHandler(ptr) {};
~ConsoleViewHandler()
~ConsoleViewHandler (void) virtual
{};
Member Function Documentation
getClassName()
const char * getClassName (void) virtual
Implements TimeHandler.
{
  return( "ConsoleViewHandler");
}
updateTime()
void updateTime (Timestamp & timestamp) virtual
Reimplemented from TimeHandler.
{
  char timestampStrBuffer[ Timestamp::getStringBufferSize()];
  Serial.printf("(%10s) %s\n",
                 timestamp.getDayOfWeekAsString(),
                 timestamp.toString( timestampStrBuffer));
  TimeHandler::updateTime( timestamp);
}
References Timestamp::getDayOfWeekAsString(), Timestamp::getStringBufferSize(), Timestamp::toString(), and TimeHandler::updateTime().
Member Data Documentation
lastTimestamp
Timestamp lastTimestamp private
The documentation for this class was generated from the following files:
ConsoleViewHandler.h
ConsoleViewHandler.cpp