My Project: Timer
Timer
#include "Timer.h"
Public Member Functions
Timer (Timer &t)
Timer (uint32_t interval)
~Timer (void)
void delay (void)
void forceTimeout (void)
bool getForceTimeoutFlagg (void)
uint32_t getInterval (void)
bool isTimeout (void)
Timer & operator= (Timer &t)
void run (void(*ptr_action)(void))
void setForceTimeoutFlagg (bool flagg)
void setInterval (uint32_t interval)
Private Attributes
bool forceTimeoutFlagg
uint32_t interval
Detailed Description
Constructor & Destructor Documentation
Timer() [1/2]
Timer (uint32_t interval)
:interval(interval), forceTimeoutFlagg(false) {}
Timer() [2/2]
Timer (Timer & t)
{
  interval= t.interval;
}
References interval.
~Timer()
~Timer (void)
{}
Member Function Documentation
delay()
void delay (void)
{
  run( nullptr);
}
References run().
Referenced by AnalogClockViewHandler::moveHands(), AnalogClockViewHandler::moveOnlyMinuteHand(), and AnalogClockViewHandler::moveOnlySecondHand().
forceTimeout()
void forceTimeout (void)
{
  forceTimeoutFlagg= true;
}
References forceTimeoutFlagg.
getForceTimeoutFlagg()
bool getForceTimeoutFlagg (void)
{
  return( forceTimeoutFlagg);
}
References forceTimeoutFlagg.
Referenced by isTimeout().
getInterval()
uint32_t getInterval (void)
{
  return( interval);
}
References interval.
isTimeout()
bool isTimeout (void)
{
  static uint32_t previous_Millis= millis();
  uint32_t  currentMillis;
  currentMillis = millis();
  if(( getForceTimeoutFlagg() || (currentMillis - previous_Millis) >= interval))
  {
    previous_Millis = currentMillis;
    // save the last time
//    Serial.printf("Timestamp: %s",   Timestamp(currentMillis - previous_Millis).toString());
    setForceTimeoutFlagg( false);
    return( true);
  }
  yield();
  return( false);
}
References getForceTimeoutFlagg(), interval, and setForceTimeoutFlagg().
Referenced by run(), showVersion(), and SystemTimeHandler::updateTime().
operator=()
Timer & operator= (Timer & t)
{
  interval= t.interval;
  return( *this);
}
References interval.
run()
void run (void(*)(void) ptr_action)
{
  while( !isTimeout())
  {
   yield();
  };
  if( ptr_action!= nullptr)
  {
    (*ptr_action)();
    yield();
  }
}
References isTimeout().
Referenced by delay(), and Timeline< T >::execute().
setForceTimeoutFlagg()
void setForceTimeoutFlagg (bool flagg)
{
  forceTimeoutFlagg= flagg;
}
References forceTimeoutFlagg.
Referenced by isTimeout().
setInterval()
void setInterval (uint32_t interval)
{
  this->interval= interval;
}
References interval.
Referenced by Timeline< T >::execute().
Member Data Documentation
forceTimeoutFlagg
bool forceTimeoutFlagg private
Referenced by forceTimeout(), getForceTimeoutFlagg(), and setForceTimeoutFlagg().
interval
uint32_t interval private
Referenced by Timer(), getInterval(), isTimeout(), operator=(), and setInterval().
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp