My Project: TimeZoneDSTHandler
TimeZoneDSTHandler
#include "TimeZoneDSTHandler.h"
Public Member Functions
TimeZoneDSTHandler (TimeHandler *ptr, uint16_t summerTimeOffset)
virtual ~TimeZoneDSTHandler (void)
virtual const char * getClassName (void)
virtual void updateTime (Timestamp &timestamp)
Public Member Functions inherited from TimeHandler
TimeHandler (TimeHandler *ptr=nullptr)
virtual ~TimeHandler (void)
virtual void bypass (bool bypassModule)
virtual const char * getClassName (void)=0
virtual bool isValidTime (void)
virtual void setValidTime (bool validFlagg)
virtual void updateTime (Timestamp &timestamp)
Private Attributes
uint16_t currentTimeOffset
Timestamp dSTEndTimestamp
Timestamp dSTStartTimestamp
Timestamp localTimestamp
const uint16_t standardTimeOffset
Additional Inherited Members
Protected Attributes inherited from TimeHandler
bool bypassModule
TimeHandler * ptr
bool validTime
Detailed Description
Constructor & Destructor Documentation
TimeZoneDSTHandler()
TimeZoneDSTHandler (TimeHandler * ptr, uint16_t summerTimeOffset)
  :TimeHandler( ptr), standardTimeOffset(standardTimeOffset), currentTimeOffset( standardTimeOffset)
{
  MyTime  time( 1,0,0); // 1:0:0  change time on 1st am universal time
  dSTStartTimestamp.setTime( time);
  dSTEndTimestamp.setTime( time);
};
References dSTEndTimestamp, dSTStartTimestamp, and Timestamp::setTime().
~TimeZoneDSTHandler()
~TimeZoneDSTHandler (void) virtual
{};
Member Function Documentation
getClassName()
const char * getClassName (void) virtual
Implements TimeHandler.
{
  return("TimeZoneDSTHandler");
}
updateTime()
void updateTime (Timestamp & timestamp) virtual
Reimplemented from TimeHandler.
{
  static  uint16_t  lastYear=0;
  MyDate  date= timestamp.getDate();
  if( date.getYear() != lastYear)
  {
    lastYear= date.getYear();
    MyDate dSTdate;
    dSTdate= MyDate::getDSTStart( date.getYear());
    dSTStartTimestamp.setDate( dSTdate);
    dSTdate= MyDate::getDSTEnd( date.getYear());
    dSTEndTimestamp.setDate( dSTdate);
    char dateStrBuffer[ MyDate::getStringBufferSize()];
    Serial.printf("\nNew DSTstart:  %s ", dSTStartTimestamp.getDate().toString( dateStrBuffer));
    Serial.printf("-  New DSTend: %s\n",  dSTEndTimestamp.getDate().toString( dateStrBuffer));
  }
  // compare timestamps
  if( timestamp == dSTStartTimestamp)
  {
    currentTimeOffset= standardTimeOffset+ SECS_PER_HOUR;
  }
  else
  if( timestamp == dSTEndTimestamp)
  {
    currentTimeOffset= standardTimeOffset;
  }
  localTimestamp= timestamp +currentTimeOffset;
  TimeHandler::updateTime( localTimestamp);
}
References currentTimeOffset, dSTEndTimestamp, dSTStartTimestamp, Timestamp::getDate(), MyDate::getDSTEnd(), MyDate::getDSTStart(), MyDate::getStringBufferSize(), MyDate::getYear(), localTimestamp, SECS_PER_HOUR, Timestamp::setDate(), standardTimeOffset, MyDate::toString(), and TimeHandler::updateTime().
Member Data Documentation
currentTimeOffset
uint16_t currentTimeOffset private
Referenced by updateTime().
dSTEndTimestamp
Timestamp dSTEndTimestamp private
Referenced by TimeZoneDSTHandler(), and updateTime().
dSTStartTimestamp
Timestamp dSTStartTimestamp private
Referenced by TimeZoneDSTHandler(), and updateTime().
localTimestamp
Timestamp localTimestamp private
Referenced by updateTime().
standardTimeOffset
const uint16_t standardTimeOffset private
Referenced by updateTime().
The documentation for this class was generated from the following files:
TimeZoneDSTHandler.h
TimeZoneDSTHandler.cpp