My Project: LEDClockViewHandler
LEDClockViewHandler
#include "LEDClockViewHandler.h"
Public Member Functions
LEDClockViewHandler (TimeHandler *ptr, const int STB_pin, const int CLK_pin, const int DIO_pin)
virtual ~LEDClockViewHandler (void)
virtual const char * getClassName (void)
virtual void updateTime (Timestamp &timestamp)
Public Member Functions inherited from TimeHandler
TimeHandler (TimeHandler *ptr=nullptr)
virtual ~TimeHandler (void)
virtual void bypass (bool bypassModule)
virtual const char * getClassName (void)=0
virtual bool isValidTime (void)
virtual void setValidTime (bool validFlagg)
virtual void updateTime (Timestamp &timestamp)
Private Member Functions
void doAction (void(*fun)(void))
Private Attributes
MyTime clockTimePresented
TM1638plus tm
Additional Inherited Members
Protected Attributes inherited from TimeHandler
bool bypassModule
TimeHandler * ptr
bool validTime
Detailed Description
Constructor & Destructor Documentation
LEDClockViewHandler()
LEDClockViewHandler (TimeHandler * ptr, const int STB_pin, const int CLK_pin, const int DIO_pin)
  :TimeHandler( ptr), tm( STB_pin, CLK_pin ,DIO_pin, false)
{
  pinMode( STB_pin, OUTPUT);
  pinMode( CLK_pin, OUTPUT);
  pinMode( DIO_pin, OUTPUT);
  tm.displayBegin();
};
References CLK_pin, DIO_pin, TM1638plus::displayBegin(), STB_pin, and tm.
~LEDClockViewHandler()
~LEDClockViewHandler (void) virtual
{};
Member Function Documentation
doAction()
void doAction (void(*)(void) fun) private
{
  (*fun)();
}
getClassName()
const char * getClassName (void) virtual
Implements TimeHandler.
{
  return("LEDClockViewHandler");
}
updateTime()
void updateTime (Timestamp & timestamp) virtual
Reimplemented from TimeHandler.
{
  MyTime    requiredTime;
  requiredTime= timestamp.getTime();
  char timeStrBuffer2[ MyTime::getStringBufferSize()];
  std::string s= requiredTime.toString( timeStrBuffer2);
  //  Serial.printf( "->%s\n",s);
  std::replace( s.begin(), s.end(), ':', '-');
  tm.displayText( s.c_str());
  //  Serial.printf( "=>%s\n",s);
  tm.setLEDs(0x0000);
  tm.setLED( timestamp.getDayOfWeek(), 1);
  TimeHandler::updateTime( timestamp);
}
References TM1638plus::displayText(), Timestamp::getDayOfWeek(), MyTime::getStringBufferSize(), Timestamp::getTime(), TM1638plus::setLED(), TM1638plus::setLEDs(), tm, MyTime::toString(), and TimeHandler::updateTime().
Member Data Documentation
clockTimePresented
MyTime clockTimePresented private
tm
TM1638plus tm private
Referenced by LEDClockViewHandler(), and updateTime().
The documentation for this class was generated from the following files:
LEDClockViewHandler.h
LEDClockViewHandler.cpp