My Project: NTPWiFiTimeHandler
NTPWiFiTimeHandler
#include "NTPWiFiTimeHandler.h"
Public Member Functions
NTPWiFiTimeHandler (TimeHandler *ptr, unsigned long updateInterval)
virtual ~NTPWiFiTimeHandler (void)
virtual const char * getClassName (void)
void init (const char *hostName)
virtual void updateTime (Timestamp &timestamp)
Public Member Functions inherited from TimeHandler
TimeHandler (TimeHandler *ptr=nullptr)
virtual ~TimeHandler (void)
virtual void bypass (bool bypassModule)
virtual const char * getClassName (void)=0
virtual bool isValidTime (void)
virtual void setValidTime (bool validFlagg)
virtual void updateTime (Timestamp &timestamp)
Private Attributes
WiFiUDP ntpUDP
NTPClient timeClient
Additional Inherited Members
Protected Attributes inherited from TimeHandler
bool bypassModule
TimeHandler * ptr
bool validTime
Detailed Description
Constructor & Destructor Documentation
NTPWiFiTimeHandler()
NTPWiFiTimeHandler (TimeHandler * ptr, unsigned long updateInterval)
        :TimeHandler( ptr), timeClient( ntpUDP)
{
  timeClient.setUpdateInterval( updateInterval);
}
References timeClient.
~NTPWiFiTimeHandler()
~NTPWiFiTimeHandler (void) virtual
{}
Member Function Documentation
getClassName()
const char * getClassName (void) virtual
Implements TimeHandler.
{
  return("NTPWiFiTimeHandler");
}
init()
void init (const char * hostName)
{
  WiFi.mode(WIFI_STA); // explicitly set mode, esp defaults to STA+AP
  WiFi.setPhyMode(WIFI_PHY_MODE_11G);
  WiFi.hostname( hostName);
  //reset settings - wipe credentials for testing
  //wm.resetSettings();
  wm.setDebugOutput( false);
  wm.addParameter( &ntpserverparam);
  wm.setConfigPortalBlocking( true);
  //Register event handlers
  wifiConnectHandler = WiFi.onStationModeGotIP(  onWifiConnect);
  wifiDisconnectHandler = WiFi.onStationModeDisconnected( onWifiDisconnect);
  //automatically connect using saved credentials if they exist
  //If connection fails it starts an access point with the specified name
  // wait for clients
  Serial.println("Config portal running");
//  wm.autoConnect(AUTOCONNECT_SSID);
  wm.autoConnect();
  Serial.println("Config portal stop");
  Serial.printf("NTP server: %s\n", ntpserverparam.getValue());
  timeClient.setPoolServerName( ntpserverparam.getValue());
}
References ntpserverparam(), onWifiConnect(), onWifiDisconnect(), timeClient, wifiConnectHandler, wifiDisconnectHandler, and wm.
updateTime()
void updateTime (Timestamp & timestamp) virtual
Reimplemented from TimeHandler.
{
  if( bypassModule)
  {
    TimeHandler::updateTime( timestamp);
    return;
  }
  if( WiFi.status()== WL_CONNECTED)
  {
  //  Serial.printf( "\nNTP adjust: step 1\n");
    timeClient.begin();
  //  Serial.printf( "NTP adjust: step 2\n");
    if( timeClient.update())
    {
      Timestamp  lastTimestamp= timestamp;
      timestamp.setEpochTime( timeClient.getEpochTime());
      char timeStrBuffer[ MyTime::getStringBufferSize()];
      Serial.printf( "                                          Current time:  %s ",           timestamp.getTime().toString( timeStrBuffer));
      Serial.printf( "---------------------------->             NTP adjust: Last time: %s  \n", lastTimestamp.getTime().toString( timeStrBuffer));
    }
    timeClient.end();
  }
  TimeHandler::updateTime( timestamp);
}
References TimeHandler::bypassModule, MyTime::getStringBufferSize(), Timestamp::getTime(), Timestamp::setEpochTime(), timeClient, MyTime::toString(), and TimeHandler::updateTime().
Member Data Documentation
ntpUDP
WiFiUDP ntpUDP private
timeClient
NTPClient timeClient private
Referenced by NTPWiFiTimeHandler(), init(), and updateTime().
The documentation for this class was generated from the following files:
NTPWiFiTimeHandler.h
NTPWiFiTimeHandler.cpp