My Project: Timestamp
Timestamp
#include "Timestamp.h"
Public Member Functions
Timestamp (const Timestamp &t)
Timestamp (uint32_t epoch=0L)
~Timestamp (void)
MyDate getDate (void) const
int getDayOfWeek (void)
const char * getDayOfWeekAsString (void)
uint32_t getEpochTime (void) const
MyTime getTime (void) const
bool operator!= (const Timestamp &t)
Timestamp operator+ (const Timestamp &t)
Timestamp operator++ (int)
Timestamp & operator++ (void)
Timestamp & operator+= (const Timestamp &t)
Timestamp operator- (const Timestamp &t)
Timestamp & operator-= (const Timestamp &t)
bool operator< (const Timestamp &t)
bool operator<= (const Timestamp &t)
Timestamp & operator= (const Timestamp &t)
bool operator== (const Timestamp &t)
bool operator> (const Timestamp &t)
bool operator>= (const Timestamp &t)
void setDate (MyDate &date)
void setEpochTime (const uint32_t newEpochTime)
void setTime (MyTime &time)
char * toString (char *Stringbuffer)
Static Public Member Functions
static size_t getStringBufferSize (void)
Private Member Functions
uint16_t sumDaysOfFullMonths (uint8_t month) const
uint32_t sumDaysOfFullYearsSinceBase (uint32_t year) const
Private Attributes
uint32_t epoch
Detailed Description
Constructor & Destructor Documentation
Timestamp() [1/2]
Timestamp (uint32_t epoch = 0L)
:epoch(epoch) {};
Timestamp() [2/2]
Timestamp (const Timestamp & t)
:epoch(t.epoch) {};
~Timestamp()
~Timestamp (void)
{};
Member Function Documentation
getDate()
MyDate getDate (void) const
{
    //                      1   2   3   4   5   6   7   8   9   10  11  12
    const uint8_t dofm[]={ 31, 28, 31, 30, 31, 30, 31, 31, 30,  31, 30, 31};
    // calucate year and rest of days
    uint32_t days= this->epoch/ SECS_PER_DAY;
    uint16_t year= BASE_YEAR;
    while( days >= DAYS_IN_YEAR( year))
    {
        days-= DAYS_IN_YEAR( year);
        year++;
    };
    // calculate months and day
    uint8_t month;
    for( month= BASE_MONTH; month <=12; month++)
    {
        if(( month== 2) && IS_LEAP_YEAR( year))
        {
          days--;
        }
        if( days < dofm[ month -1])
        {
          break;
        }
        days -=  dofm[ month -1];
    }
    MyDate  date;
    date.setYear( year);
    date.setMonth( month);
    date.setDay( days +BASE_DAY);
    return( date);
}
References BASE_DAY, BASE_MONTH, BASE_YEAR, DAYS_IN_YEAR, epoch, IS_LEAP_YEAR, SECS_PER_DAY, MyDate::setDay(), MyDate::setMonth(), and MyDate::setYear().
Referenced by SystemTimeHandler::adjust(), getDayOfWeek(), toString(), OLEDDisplayClockViewHandler::updateTime(), TimeSunriseSunsetHandler::updateTime(), and TimeZoneDSTHandler::updateTime().
getDayOfWeek()
int getDayOfWeek (void)
{
  return( getDate().getDayOfWeek());
}
References getDate(), and getDayOfWeek().
Referenced by getDayOfWeek(), getDayOfWeekAsString(), and LEDClockViewHandler::updateTime().
getDayOfWeekAsString()
const char * getDayOfWeekAsString (void)
{
  const char* dayOfWeekAsString[]={ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"};
  return( dayOfWeekAsString[ getDayOfWeek()]);
}
References getDayOfWeek().
Referenced by ConsoleViewHandler::updateTime().
getEpochTime()
uint32_t getEpochTime (void) const
{
  return( epoch);
}
References epoch.
Referenced by SplitterTimeHandler::updateTime().
getStringBufferSize()
size_t getStringBufferSize (void) static
{
  return( strlen( MyDate::getStringFormat())+ strlen(" - ")+ strlen( MyTime::getStringFormat()));
}
References MyDate::getStringFormat(), and MyTime::getStringFormat().
Referenced by ConsoleViewHandler::updateTime().
getTime()
MyTime getTime (void) const
{
    uint32_t days= this->epoch% SECS_PER_DAY;
    MyTime  time;
    time.setHour( days / SECS_PER_HOUR);
    uint16_t seconds= days % SECS_PER_HOUR;
    time.setMinute( seconds / SECS_PER_MIN);
    time.setSecond( seconds % SECS_PER_MIN);
    return( time);
}
References epoch, SECS_PER_DAY, SECS_PER_HOUR, SECS_PER_MIN, MyTime::setHour(), MyTime::setMinute(), and MyTime::setSecond().
Referenced by SystemTimeHandler::adjust(), toString(), AnalogClockViewHandler::updateTime(), LEDClockViewHandler::updateTime(), NTPWiFiTimeHandler::updateTime(), and OLEDDisplayClockViewHandler::updateTime().
operator!=()
bool operator!= (const Timestamp & t)
{
  return( epoch!= t.epoch);
}
References epoch.
operator+()
Timestamp operator+ (const Timestamp & t)
{
  Timestamp temp;
  temp.epoch = epoch + t.epoch;
  return temp;
};
References epoch.
operator++() [1/2]
Timestamp operator++ (int)
{
  epoch++;
  return( *this);
}
References epoch.
operator++() [2/2]
Timestamp & operator++ (void)
{
  epoch++;
  return( *this);
}
References epoch.
operator+=()
Timestamp & operator+= (const Timestamp & t)
{
   epoch = epoch + t.epoch;
   return *this;
}
References epoch.
operator-()
Timestamp operator- (const Timestamp & t)
{
  Timestamp temp;
  temp.epoch = epoch - t.epoch;
  return temp;
};
References epoch.
operator-=()
Timestamp & operator-= (const Timestamp & t)
{
   epoch = epoch - t.epoch;
   return *this;
}
References epoch.
operator<()
bool operator< (const Timestamp & t)
{
  return( epoch < t.epoch);
};
References epoch.
operator<=()
bool operator<= (const Timestamp & t)
{
  return( epoch <= t.epoch);
};
References epoch.
operator=()
Timestamp & operator= (const Timestamp & t)
{
  if( &t != this)
  {
    epoch= t.epoch;
  }
  return( *this);
}
References epoch.
operator==()
bool operator== (const Timestamp & t)
{
  return( epoch== t.epoch);
}
References epoch.
operator>()
bool operator> (const Timestamp & t)
{
  return( epoch > t.epoch);
};
References epoch.
operator>=()
bool operator>= (const Timestamp & t)
{
  return( epoch >= t.epoch);
};
References epoch.
setDate()
void setDate (MyDate & date)
{
    uint32_t  days= 0;
    days  = sumDaysOfFullYearsSinceBase( date.getYear());
    days += sumDaysOfFullMonths( date.getMonth());
    days += date.getDay() -BASE_DAY;
    epoch = epoch %SECS_PER_DAY;
    epoch += (days  *SECS_PER_DAY);
}
References BASE_DAY, epoch, MyDate::getDay(), MyDate::getMonth(), MyDate::getYear(), SECS_PER_DAY, sumDaysOfFullMonths(), and sumDaysOfFullYearsSinceBase().
Referenced by SystemTimeHandler::adjust(), and TimeZoneDSTHandler::updateTime().
setEpochTime()
void setEpochTime (const uint32_t newEpochTime)
{
  epoch= newEpochTime;
}
References epoch.
Referenced by NTPWiFiTimeHandler::updateTime(), and SplitterTimeHandler::updateTime().
setTime()
void setTime (MyTime & time)
{
    this->epoch= ( this->epoch / SECS_PER_DAY) *SECS_PER_DAY;
    this->epoch+= time.getHour()   *SECS_PER_HOUR;
    this->epoch+= time.getMinute() *SECS_PER_MIN;
    this->epoch+= time.getSecond();
}
References epoch, MyTime::getHour(), MyTime::getMinute(), MyTime::getSecond(), SECS_PER_DAY, SECS_PER_HOUR, and SECS_PER_MIN.
Referenced by TimeZoneDSTHandler::TimeZoneDSTHandler(), and SystemTimeHandler::adjust().
sumDaysOfFullMonths()
uint16_t sumDaysOfFullMonths (uint8_t month) const private
{
    uint16_t  days= 0;
    //                     0   1   2   3   4   5   6   7   8   9   10  11  12
    const uint8_t dofm[]={ 0, 31, 28, 31, 30, 31, 30, 31, 31, 30,  31, 30, 31};
    for( uint8_t m=0; m< month; m++)
    {
      days += dofm[ m];
    }
    return( days);
}
Referenced by setDate().
sumDaysOfFullYearsSinceBase()
uint32_t sumDaysOfFullYearsSinceBase (uint32_t year) const private
{
  uint32_t sum=0;
  for( uint16_t y= BASE_YEAR; y< year; y++)
  {
    sum += DAYS_IN_YEAR( y);
  }
  return( sum);
}
References BASE_YEAR, and DAYS_IN_YEAR.
Referenced by setDate().
toString()
char * toString (char * Stringbuffer)
{
  MyDate date= getDate();
  MyTime time= getTime();
  char dateStrBuffer[ MyDate::getStringBufferSize()];
  char timeStrBuffer[ MyTime::getStringBufferSize()];
  sprintf( ptr, "%s -  %s", date.toString( dateStrBuffer), time.toString( timeStrBuffer));
  return( ptr);
}
References getDate(), MyDate::getStringBufferSize(), MyTime::getStringBufferSize(), getTime(), MyDate::toString(), and MyTime::toString().
Referenced by ConsoleViewHandler::updateTime().
Member Data Documentation
epoch
uint32_t epoch private
Referenced by getDate(), getEpochTime(), getTime(), operator!=(), operator+(), operator++(), operator+=(), operator-(), operator-=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), setDate(), setEpochTime(), and setTime().
The documentation for this class was generated from the following files:
Timestamp.h
Timestamp.cpp