My Project: TM1638plus_Model2
TM1638plus_Model2
#include "TM1638plus_Model2.h"
Public Member Functions
TM1638plus_Model2 (uint8_t strobe, uint8_t clock, uint8_t data, bool swap_nibbles=false, bool high_freq=false)
void ASCIItoSegment (const byte values[])
void brightness (uint8_t brightness)
void displayBegin (void)
void DisplayDecNum (unsigned long number, byte dots, boolean leadingZeros=true, AlignTextType_e=TMAlignTextLeft)
void DisplayDecNumNibble (uint16_t numberUpper, uint16_t numberLower, byte dots, boolean leadingZeros=true, AlignTextType_e=TMAlignTextLeft)
void DisplayHexNum (uint16_t numberUpper, uint16_t numberLower, byte dots, boolean leadingZeros=true, AlignTextType_e=TMAlignTextLeft)
void DisplaySegments (uint8_t segment, uint8_t segmentValue)
void DisplayStr (const char *string, const word dots=0)
uint8_t ReadKey16 (void)
uint16_t ReadKey16Two (void)
void reset (void)
Private Member Functions
void sendCommand (uint8_t value)
void sendData (uint8_t data)
Private Attributes
uint8_t _CLOCK_IO
uint8_t _DATA_IO
bool _HIGH_FREQ = false
uint8_t _STROBE_IO
bool _SWAP_NIBBLES = false
TM1638plus_common TM_common
Detailed Description
Constructor & Destructor Documentation
TM1638plus_Model2()
TM1638plus_Model2 (uint8_t strobe, uint8_t clock, uint8_t data, bool swap_nibbles = false, bool high_freq = false)
{
  _STROBE_IO = strobe;
  _DATA_IO = data;
  _CLOCK_IO = clock;
  _SWAP_NIBBLES = swap_nibbles;
  _HIGH_FREQ = high_freq;
}
References _CLOCK_IO, _DATA_IO, _HIGH_FREQ, _STROBE_IO, and _SWAP_NIBBLES.
Member Function Documentation
ASCIItoSegment()
void ASCIItoSegment (const byte values[])
{
  for (uint8_t  segment = 0; segment < TM_DISPLAY_SIZE; segment++) {
  uint8_t  SegmentValue = 0;
  for (uint8_t  j = 0; j < TM_DISPLAY_SIZE; j++) {
    SegmentValue |= ((values[j] >> segment) & 1) << (TM_DISPLAY_SIZE - j - 1);
  }
  DisplaySegments(segment , SegmentValue);
  }
}
References DisplaySegments(), and TM_DISPLAY_SIZE.
Referenced by DisplayStr().
brightness()
void brightness (uint8_t brightness)
{
    uint8_t  value = 0;
    value = TM_BRIGHT_ADR + (TM_BRIGHT_MASK & brightness);
    sendCommand(value);
}
References brightness(), sendCommand(), TM_BRIGHT_ADR, and TM_BRIGHT_MASK.
Referenced by brightness(), and displayBegin().
displayBegin()
void displayBegin (void)
{
  pinMode(_STROBE_IO, OUTPUT);
  pinMode(_DATA_IO, OUTPUT);
  pinMode(_CLOCK_IO, OUTPUT);
  sendCommand(TM_ACTIVATE);
  brightness(TM_DEFAULT_BRIGHTNESS);
  reset();
}
References _CLOCK_IO, _DATA_IO, _STROBE_IO, brightness(), reset(), sendCommand(), TM_ACTIVATE, and TM_DEFAULT_BRIGHTNESS.
DisplayDecNum()
void DisplayDecNum (unsigned long number, byte dots, boolean leadingZeros = true, AlignTextType_e TextAlignment = TMAlignTextLeft)
{
  char values[TM_DISPLAY_SIZE + 1];
  char TextDisplay[5] = "%";
  char TextLeft[3] = "ld";
  char TextRight[4] = "8ld";
    if (TextAlignment == TMAlignTextLeft)
    {
        strcat(TextDisplay ,TextLeft);  // %ld
    }else if ( TextAlignment == TMAlignTextRight)
    {
        strcat(TextDisplay ,TextRight); // %8ld
    }
  snprintf(values, TM_DISPLAY_SIZE + 1, leadingZeros ? "%08ld" : TextDisplay, number);
  DisplayStr(values, dots);
}
References DisplayStr(), TM_DISPLAY_SIZE, TMAlignTextLeft, and TMAlignTextRight.
DisplayDecNumNibble()
void DisplayDecNumNibble (uint16_t numberUpper, uint16_t numberLower, byte dots, boolean leadingZeros = true, AlignTextType_e TextAlignment = TMAlignTextLeft)
{
  char valuesUpper[TM_DISPLAY_SIZE + 1];
  char valuesLower[TM_DISPLAY_SIZE/2 + 1];
  char TextDisplay[5] = "%";
  char TextLeft[4] = "-4d";
  char TextRight[3] = "4d";
     if (TextAlignment == TMAlignTextLeft)
    {
        strcat(TextDisplay ,TextLeft);  // %-4d
    }else if ( TextAlignment == TMAlignTextRight)
    {
        strcat(TextDisplay ,TextRight); // %4d
    }
  snprintf(valuesUpper, TM_DISPLAY_SIZE/2 + 1, leadingZeros ? "%04d" : TextDisplay, numberUpper);
  snprintf(valuesLower, TM_DISPLAY_SIZE/2 + 1, leadingZeros ? "%04d" : TextDisplay, numberLower);
  strcat(valuesUpper ,valuesLower);
  DisplayStr(valuesUpper, dots);
}
References DisplayStr(), TM_DISPLAY_SIZE, TMAlignTextLeft, and TMAlignTextRight.
DisplayHexNum()
void DisplayHexNum (uint16_t numberUpper, uint16_t numberLower, byte dots, boolean leadingZeros = true, AlignTextType_e TextAlignment = TMAlignTextLeft)
{
  char valuesUpper[TM_DISPLAY_SIZE + 1];
  char valuesLower[TM_DISPLAY_SIZE/2 + 1];
  char TextDisplay[5] = "%";
  char TextLeft[4] = "-4X";
  char TextRight[3] = "4X";
     if (TextAlignment == TMAlignTextLeft)
    {
        strcat(TextDisplay ,TextLeft);  // %-4X
    }else if ( TextAlignment = TMAlignTextRight)
    {
        strcat(TextDisplay ,TextRight); // %4X
    }
  snprintf(valuesUpper, TM_DISPLAY_SIZE/2 + 1, leadingZeros ? "%04X" : TextDisplay, numberUpper);
  snprintf(valuesLower, TM_DISPLAY_SIZE/2 + 1, leadingZeros ? "%04X" : TextDisplay, numberLower);
  strcat(valuesUpper ,valuesLower);
  DisplayStr(valuesUpper, dots);
}
References DisplayStr(), TM_DISPLAY_SIZE, TMAlignTextLeft, and TMAlignTextRight.
DisplaySegments()
void DisplaySegments (uint8_t segment, uint8_t segmentValue)
{
   if (_SWAP_NIBBLES == true)
   {
      uint8_t upper , lower = 0;
      lower = (digit) & 0x0F;  // select lower nibble
      upper =  (digit >> 4) & 0X0F; //select upper nibble
      digit = lower << 4 | upper;
   }
  segment = (segment<<1);
  sendCommand(TM_WRITE_LOC);
  digitalWrite(_STROBE_IO, LOW);
  sendData(TM_SEG_ADR | segment);
  sendData(digit);
  digitalWrite(_STROBE_IO, HIGH);
}
References _STROBE_IO, _SWAP_NIBBLES, sendCommand(), sendData(), TM_SEG_ADR, and TM_WRITE_LOC.
Referenced by ASCIItoSegment().
DisplayStr()
void DisplayStr (const char * string, const word dots = 0)
{
  byte values[TM_DISPLAY_SIZE];
  boolean done = false;
  uint8_t Result  = 0;
  memset(values, 0, TM_DISPLAY_SIZE * sizeof(byte));
  for (uint8_t  i = 0; i < TM_DISPLAY_SIZE; i++)
  {
       if (!done && string[i] != '\0') {
         if (dots >> (7-i) & 1){  //if dots bit is set for that position apply the mask to turn on dot(0x80).
            Result = pgm_read_byte(&SevenSeg[string[i] - TM_ASCII_OFFSET]);
            values[i] = (Result | TM_DOT_MASK_DEC); //apply the Dot bitmask to value extracted from ASCII table
            }
          else
            values[i] = pgm_read_byte(&SevenSeg[string[i] - TM_ASCII_OFFSET]) ;
        }
      else {
        done = true;
        values[i] = (((dots >> (7 - i)) & 1) << 7);
        }
  }
 ASCIItoSegment(values);
}
References ASCIItoSegment(), SevenSeg, TM_ASCII_OFFSET, TM_DISPLAY_SIZE, and TM_DOT_MASK_DEC.
Referenced by DisplayDecNum(), DisplayDecNumNibble(), and DisplayHexNum().
ReadKey16()
unsigned char ReadKey16 (void)
{
  unsigned char c[4], i, key_value=0;
  digitalWrite(_STROBE_IO, LOW);
  sendData(TM_BUTTONS_MODE);
  pinMode(_DATA_IO, INPUT);
  for (i = 0; i < 4; i++)
  {
      if  (_HIGH_FREQ == false)
        c[i] = shiftIn(_DATA_IO, _CLOCK_IO, LSBFIRST);
     else
        c[i] =  TM_common.HighFreqshiftin(_DATA_IO, _CLOCK_IO, LSBFIRST);
     if (c[i] == 0x04) key_value = 1 + (2*i); //00000100 4 0x04
     if (c[i] == 0x40) key_value = 2 + (2*i); //01000000 64 0x40
     if (c[i] == 0x02) key_value = 9 + (2*i); //00000010 2 0x02
     if (c[i] == 0x20) key_value = 10 + (2*i);  //00100000 32 0x20
  }
  pinMode(_DATA_IO, OUTPUT);
  digitalWrite(_STROBE_IO, HIGH);
  return (key_value);
  // Data matrix for read key_value.
  // c3 0110 0110  c2 0110 0110  c1 0110 0110  c0 0110 0110 :bytes read
  //    8,16 7,15     6,14 5,13     4,12 3,11     2,10  1,9 :button value
}
References _CLOCK_IO, _DATA_IO, _HIGH_FREQ, _STROBE_IO, TM1638plus_common::HighFreqshiftin(), sendData(), TM_BUTTONS_MODE, and TM_common.
ReadKey16Two()
uint16_t ReadKey16Two (void)
{
  uint16_t key_value = 0;
  uint8_t Datain ,i = 0;
  digitalWrite(_STROBE_IO, LOW);
  sendData(TM_BUTTONS_MODE);
  pinMode(_DATA_IO, INPUT);
  for (i = 0; i < 4; i++)
  {
      if  (_HIGH_FREQ == false)
        Datain = shiftIn(_DATA_IO, _CLOCK_IO, LSBFIRST);
     else
        Datain =  TM_common.HighFreqshiftin(_DATA_IO, _CLOCK_IO, LSBFIRST);
      // turn Datain ABCDEFGI = 0BC00FG0  into 00CG00BF see matrix below
      Datain = (((Datain & 0x40) >> 3 | (Datain & 0x04)) >> 2) | (Datain & 0x20) | (Datain & 0x02) << 3;
     // i = 0 Datain =  00,10,9,0021 // i = 1 Datain  = 00,12,11,0043
     // i = 2 Datain =  00 ,14,13,0065 // i = 3 Datain =  00,16,15,0087
     // key_value =  16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1.
      key_value |= ((Datain & 0x000F) << (2*i)) | (((Datain & 0x00F0) << 4) << (2*i));
  }
  pinMode(_DATA_IO, OUTPUT);
  digitalWrite(_STROBE_IO, HIGH);
  return (key_value);
  //  Data matrix for read key_value. c = datain
  //   c3 0110 0110  c2 0110 0110  c1 0110 0110  c0 0110 0110 :bytes read
  //    8,16 7,15     6,14 5,13     4,12 3,11                   2,10  1,9 :button value
}
References _CLOCK_IO, _DATA_IO, _HIGH_FREQ, _STROBE_IO, TM1638plus_common::HighFreqshiftin(), sendData(), TM_BUTTONS_MODE, and TM_common.
reset()
void reset (void)
{
  sendCommand(TM_WRITE_INC); // set auto increment mode
  digitalWrite(_STROBE_IO, LOW);
  sendData(TM_SEG_ADR);   // set starting address to 0
  for (uint8_t position = 0; position < 16; position++)
  {
    sendData(0x00); //clear all segments
  }
   digitalWrite(_STROBE_IO, HIGH);
}
References _STROBE_IO, sendCommand(), sendData(), TM_SEG_ADR, and TM_WRITE_INC.
Referenced by displayBegin().
sendCommand()
void sendCommand (uint8_t value) private
{
  digitalWrite(_STROBE_IO, LOW);
  sendData(value);
  digitalWrite(_STROBE_IO, HIGH);
}
References _STROBE_IO, and sendData().
Referenced by brightness(), displayBegin(), DisplaySegments(), and reset().
sendData()
void sendData (uint8_t data) private
{
  if (_HIGH_FREQ == false)
    shiftOut(_DATA_IO, _CLOCK_IO, LSBFIRST, data);
  else
     TM_common.HighFreqshiftOut(_DATA_IO, _CLOCK_IO, LSBFIRST, data);
}
References _CLOCK_IO, _DATA_IO, _HIGH_FREQ, TM1638plus_common::HighFreqshiftOut(), and TM_common.
Referenced by DisplaySegments(), ReadKey16(), ReadKey16Two(), reset(), and sendCommand().
Member Data Documentation
_CLOCK_IO
uint8_t _CLOCK_IO private
Referenced by TM1638plus_Model2(), displayBegin(), ReadKey16(), ReadKey16Two(), and sendData().
_DATA_IO
uint8_t _DATA_IO private
Referenced by TM1638plus_Model2(), displayBegin(), ReadKey16(), ReadKey16Two(), and sendData().
_HIGH_FREQ
bool _HIGH_FREQ = false private
Referenced by TM1638plus_Model2(), ReadKey16(), ReadKey16Two(), and sendData().
_STROBE_IO
uint8_t _STROBE_IO private
Referenced by TM1638plus_Model2(), displayBegin(), DisplaySegments(), ReadKey16(), ReadKey16Two(), reset(), and sendCommand().
_SWAP_NIBBLES
bool _SWAP_NIBBLES = false private
Referenced by TM1638plus_Model2(), and DisplaySegments().
TM_common
TM1638plus_common TM_common private
Referenced by ReadKey16(), ReadKey16Two(), and sendData().
The documentation for this class was generated from the following files:
extra/TM1638plus-master/TM1638plus-master/src/TM1638plus_Model2.h
extra/TM1638plus-master/TM1638plus-master/src/TM1638plus_Model2.cpp