My Project: TM1638plus
TM1638plus
#include "TM1638plus.h"
Public Member Functions
TM1638plus (uint8_t strobe, uint8_t clock, uint8_t data, bool highfreq=false)
void brightness (uint8_t brightness)
void display7Seg (uint8_t position, uint8_t value)
void displayASCII (uint8_t position, uint8_t ascii)
void displayASCIIwDot (uint8_t position, uint8_t ascii)
void displayBegin ()
void DisplayDecNumNibble (uint16_t numberUpper, uint16_t numberLower, boolean leadingZeros=true, AlignTextType_e=TMAlignTextLeft)
void displayHex (uint8_t position, uint8_t hex)
void displayIntNum (unsigned long number, boolean leadingZeros=true, AlignTextType_e=TMAlignTextLeft)
void displayText (const char *text)
uint8_t readButtons (void)
void reset (void)
void setLED (uint8_t position, uint8_t value)
void setLEDs (uint16_t greenred)
Private Member Functions
void sendCommand (uint8_t value)
void sendData (uint8_t data)
Private Attributes
uint8_t _CLOCK_IO
uint8_t _DATA_IO
bool _HIGH_FREQ = false
uint8_t _STROBE_IO
TM1638plus_common TM_common
Detailed Description
Constructor & Destructor Documentation
TM1638plus()
TM1638plus (uint8_t strobe, uint8_t clock, uint8_t data, bool highfreq = false)
{
  _STROBE_IO = strobe;
  _DATA_IO = data;
  _CLOCK_IO = clock;
   _HIGH_FREQ = highfreq;
}
References _CLOCK_IO, _DATA_IO, _HIGH_FREQ, and _STROBE_IO.
Member Function Documentation
brightness()
void brightness (uint8_t brightness)
{
    uint8_t  value = 0;
    value = TM_BRIGHT_ADR + (TM_BRIGHT_MASK & brightness);
    sendCommand(value);
}
References brightness(), sendCommand(), TM_BRIGHT_ADR, and TM_BRIGHT_MASK.
Referenced by brightness(), and displayBegin().
display7Seg()
void display7Seg (uint8_t position, uint8_t value)
                                                            { // call 7-segment
  sendCommand(TM_WRITE_LOC);
  digitalWrite(_STROBE_IO, LOW);
  sendData(TM_SEG_ADR + (position << 1));
  sendData(value);
  digitalWrite(_STROBE_IO, HIGH);
}
References _STROBE_IO, sendCommand(), sendData(), TM_SEG_ADR, and TM_WRITE_LOC.
Referenced by displayASCII(), displayASCIIwDot(), and displayHex().
displayASCII()
void displayASCII (uint8_t position, uint8_t ascii)
{
  display7Seg(position, pgm_read_byte(&SevenSeg[ascii - TM_ASCII_OFFSET]));
}
References display7Seg(), SevenSeg, and TM_ASCII_OFFSET.
Referenced by displayText().
displayASCIIwDot()
void displayASCIIwDot (uint8_t position, uint8_t ascii)
{
    // add 128 or 0x080 0b1000000 to turn on decimal point/dot in seven seg
  display7Seg(position, pgm_read_byte(&SevenSeg[ascii- TM_ASCII_OFFSET]) + TM_DOT_MASK_DEC);
}
References display7Seg(), SevenSeg, TM_ASCII_OFFSET, and TM_DOT_MASK_DEC.
Referenced by displayText().
displayBegin()
void displayBegin ()
{
  pinMode(_STROBE_IO , OUTPUT);
  pinMode(_DATA_IO, OUTPUT);
  pinMode(_CLOCK_IO , OUTPUT);
  sendCommand(TM_ACTIVATE);
  brightness(TM_DEFAULT_BRIGHTNESS);
  reset();
}
References _CLOCK_IO, _DATA_IO, _STROBE_IO, brightness(), reset(), sendCommand(), TM_ACTIVATE, and TM_DEFAULT_BRIGHTNESS.
Referenced by LEDClockViewHandler::LEDClockViewHandler().
DisplayDecNumNibble()
void DisplayDecNumNibble (uint16_t numberUpper, uint16_t numberLower, boolean leadingZeros = true, AlignTextType_e TextAlignment = TMAlignTextLeft)
{
    char valuesUpper[TM_DISPLAY_SIZE + 1];
    char valuesLower[TM_DISPLAY_SIZE/2 + 1];
    char TextDisplay[5] = "%";
    char TextLeft[4] = "-4d";
    char TextRight[3] = "4d";
     if (TextAlignment == TMAlignTextLeft)
    {
        strcat(TextDisplay ,TextLeft);  // %-4d
    }else if ( TextAlignment == TMAlignTextRight)
    {
        strcat(TextDisplay ,TextRight); // %4d
    }
    snprintf(valuesUpper, TM_DISPLAY_SIZE/2 + 1, leadingZeros ? "%04d" : TextDisplay, numberUpper);
    snprintf(valuesLower, TM_DISPLAY_SIZE/2 + 1, leadingZeros ? "%04d" : TextDisplay, numberLower);
   strcat(valuesUpper ,valuesLower);
   displayText(valuesUpper);
}
References displayText(), TM_DISPLAY_SIZE, TMAlignTextLeft, and TMAlignTextRight.
displayHex()
void displayHex (uint8_t position, uint8_t hex)
{
    uint8_t offset = 0;
    hex = hex % 16;
    if (hex <= 9)
    {
        display7Seg(position, pgm_read_byte(&SevenSeg[hex + TM_HEX_OFFSET]));
        // 16 is offset in reduced ASCII table for 0
    }else if ((hex >= 10) && (hex <=15))
    {
        // Calculate offset in reduced ASCII table for AbCDeF
        switch(hex)
        {
         case 10: offset = 'A'; break;
         case 11: offset = 'b'; break;
         case 12: offset = 'C'; break;
         case 13: offset = 'd'; break;
         case 14: offset = 'E'; break;
         case 15: offset = 'F'; break;
        }
        display7Seg(position, pgm_read_byte(&SevenSeg[offset-TM_ASCII_OFFSET]));
    }
}
References display7Seg(), SevenSeg, TM_ASCII_OFFSET, and TM_HEX_OFFSET.
displayIntNum()
void displayIntNum (unsigned long number, boolean leadingZeros = true, AlignTextType_e TextAlignment = TMAlignTextLeft)
{
  char values[TM_DISPLAY_SIZE + 1];
  char TextDisplay[5] = "%";
  char TextLeft[3] = "ld";
  char TextRight[4] = "8ld";
  if (TextAlignment == TMAlignTextLeft)
    {
        strcat(TextDisplay ,TextLeft);  // %ld
    }else if ( TextAlignment == TMAlignTextRight)
    {
        strcat(TextDisplay ,TextRight); // %8ld
    }
  snprintf(values, TM_DISPLAY_SIZE + 1, leadingZeros ? "%08ld" : TextDisplay, number);
  displayText(values);
}
References displayText(), TM_DISPLAY_SIZE, TMAlignTextLeft, and TMAlignTextRight.
displayText()
void displayText (const char * text)
{
  char c, pos;
  pos = 0;
      while ((c = (*text++)) && pos < TM_DISPLAY_SIZE)  {
        if (*text == '.' && c != '.') {
          displayASCIIwDot(pos++, c);
          text++;
        }  else {
          displayASCII(pos++, c);
        }
      }
}
References displayASCII(), displayASCIIwDot(), and TM_DISPLAY_SIZE.
Referenced by DisplayDecNumNibble(), displayIntNum(), and LEDClockViewHandler::updateTime().
readButtons()
uint8_t readButtons (void)
{
  uint8_t buttons = 0;
  uint8_t v =0;
  digitalWrite(_STROBE_IO, LOW);
  sendData(TM_BUTTONS_MODE);
  pinMode(_DATA_IO, INPUT);
  for (uint8_t i = 0; i < 4; i++)
  {
    if  (_HIGH_FREQ == false)
        v = shiftIn(_DATA_IO, _CLOCK_IO, LSBFIRST) << i;
    else
        v = TM_common.HighFreqshiftin(_DATA_IO, _CLOCK_IO, LSBFIRST) << i;
    buttons |= v;
  }
  pinMode(_DATA_IO, OUTPUT);
  digitalWrite(_STROBE_IO, HIGH);
  return buttons;
}
References _CLOCK_IO, _DATA_IO, _HIGH_FREQ, _STROBE_IO, TM1638plus_common::HighFreqshiftin(), sendData(), TM_BUTTONS_MODE, and TM_common.
reset()
void reset (void)
                       {
  sendCommand(TM_WRITE_INC); // set auto increment mode
  digitalWrite(_STROBE_IO, LOW);
  sendData(TM_SEG_ADR);  // set starting address to
  for (uint8_t i = 0; i < 16; i++)
  {
    sendData(0x00);
  }
   digitalWrite(_STROBE_IO, HIGH);
}
References _STROBE_IO, sendCommand(), sendData(), TM_SEG_ADR, and TM_WRITE_INC.
Referenced by displayBegin().
sendCommand()
void sendCommand (uint8_t value) private
{
  digitalWrite(_STROBE_IO, LOW);
  sendData(value);
  digitalWrite(_STROBE_IO, HIGH);
}
References _STROBE_IO, and sendData().
Referenced by brightness(), display7Seg(), displayBegin(), reset(), and setLED().
sendData()
void sendData (uint8_t data) private
{
  if (_HIGH_FREQ == false)
    shiftOut(_DATA_IO, _CLOCK_IO, LSBFIRST, data);
  else
    TM_common.HighFreqshiftOut(_DATA_IO, _CLOCK_IO, LSBFIRST, data);
}
References _CLOCK_IO, _DATA_IO, _HIGH_FREQ, TM1638plus_common::HighFreqshiftOut(), and TM_common.
Referenced by display7Seg(), readButtons(), reset(), sendCommand(), and setLED().
setLED()
void setLED (uint8_t position, uint8_t value)
{
  pinMode(_DATA_IO, OUTPUT);
  sendCommand(TM_WRITE_LOC);
  digitalWrite(_STROBE_IO, LOW);
  sendData(TM_LEDS_ADR + (position << 1));
  sendData(value);
  digitalWrite(_STROBE_IO, HIGH);
}
References _DATA_IO, _STROBE_IO, sendCommand(), sendData(), TM_LEDS_ADR, and TM_WRITE_LOC.
Referenced by setLEDs(), and LEDClockViewHandler::updateTime().
setLEDs()
void setLEDs (uint16_t greenred)
{
  for (uint8_t LEDposition = 0;  LEDposition < 8; LEDposition++) {
    uint8_t colour = 0;
    if ((ledvalues & (1 << LEDposition)) != 0) {
      colour |= TM_RED_LED; //scan lower byte, set Red if one
    }
    if ((ledvalues & (1 << (LEDposition + 8))) != 0) {
      colour |= TM_GREEN_LED; //scan upper byte, set green if one
    }
    setLED(LEDposition, colour);
  }
}
References setLED(), TM_GREEN_LED, and TM_RED_LED.
Referenced by LEDClockViewHandler::updateTime().
Member Data Documentation
_CLOCK_IO
uint8_t _CLOCK_IO private
Referenced by TM1638plus(), displayBegin(), readButtons(), and sendData().
_DATA_IO
uint8_t _DATA_IO private
Referenced by TM1638plus(), displayBegin(), readButtons(), sendData(), and setLED().
_HIGH_FREQ
bool _HIGH_FREQ = false private
Referenced by TM1638plus(), readButtons(), and sendData().
_STROBE_IO
uint8_t _STROBE_IO private
Referenced by TM1638plus(), display7Seg(), displayBegin(), readButtons(), reset(), sendCommand(), and setLED().
TM_common
TM1638plus_common TM_common private
Referenced by readButtons(), and sendData().
The documentation for this class was generated from the following files:
extra/TM1638plus-master/TM1638plus-master/src/TM1638plus.h
extra/TM1638plus-master/TM1638plus-master/src/TM1638plus.cpp