My Project: SystemTimeHandler
SystemTimeHandler
#include "SystemTimeHandler.h"
Public Types
enum class direction { Plus , Minus }
enum class variable {
Hour , Minute , Second , Day ,
Month , Year
}
Public Member Functions
SystemTimeHandler (TimeHandler *ptr=nullptr)
~SystemTimeHandler (void)
void adjust (SystemTimeHandler::variable var, SystemTimeHandler::direction dir)
bool isInManualMode (void)
void manualMode (bool mode)
void updateTime (void)
Private Attributes
bool manualModeFlagg
TimeHandler * ptr2timeHandler
Timestamp systemTimestamp
Timer timer
Detailed Description
Member Enumeration Documentation
direction
enum class direction strong
Enumerator
Plus
Minus
{ Plus, Minus};
variable
enum class variable strong
Enumerator
Hour
Minute
Second
Day
Month
Year
{ Hour, Minute, Second, Day, Month, Year};
Constructor & Destructor Documentation
SystemTimeHandler()
SystemTimeHandler (TimeHandler * ptr = nullptr)
  :ptr2timeHandler( ptr2timeHandler), manualModeFlagg( false), timer( 940) {}   // 940
~SystemTimeHandler()
~SystemTimeHandler (void)
{}
Member Function Documentation
adjust()
void adjust (SystemTimeHandler::variable var, SystemTimeHandler::direction dir)
{
   switch( var)
   {
      case variable::Hour:
          {
            MyTime my_time( systemTimestamp.getTime());
            (dir== direction::Plus)?  my_time.hourInc(): my_time.hourDec();
            systemTimestamp.setTime( my_time);
          }
          break;
      case variable::Minute:
          {
            MyTime my_time( systemTimestamp.getTime());
            (dir== direction::Plus)?  my_time.minuteInc(): my_time.minuteDec();
            systemTimestamp.setTime( my_time);
          }
          break;
      case variable::Second:
          {
            MyTime my_time( systemTimestamp.getTime());
            (dir== direction::Plus)?  my_time.secondInc(): my_time.secondDec();
            systemTimestamp.setTime( my_time);
          }
          break;
      case variable::Day:
          {
            MyDate my_date( systemTimestamp.getDate());
            (dir== direction::Plus)?  my_date.dayInc(): my_date.dayDec();
            systemTimestamp.setDate( my_date);
          }
          break;
      case variable::Month:
          {
            MyDate my_date( systemTimestamp.getDate());
            (dir== direction::Plus)?  my_date.monthInc(): my_date.monthDec();
            systemTimestamp.setDate( my_date);
          }
          break;
      case variable::Year:
          {
            MyDate my_date( systemTimestamp.getDate());
            (dir== direction::Plus)?  my_date.yearInc(): my_date.yearDec();
            systemTimestamp.setDate( my_date);
          }
          break;
      default:
          break;
   };
   ptr2timeHandler->updateTime( systemTimestamp);
}
References Day, MyDate::dayDec(), MyDate::dayInc(), Timestamp::getDate(), Timestamp::getTime(), Hour, MyTime::hourDec(), MyTime::hourInc(), Minute, MyTime::minuteDec(), MyTime::minuteInc(), Month, MyDate::monthDec(), MyDate::monthInc(), Plus, ptr2timeHandler, Second, MyTime::secondDec(), MyTime::secondInc(), Timestamp::setDate(), Timestamp::setTime(), systemTimestamp, TimeHandler::updateTime(), Year, MyDate::yearDec(), and MyDate::yearInc().
Referenced by Controller::execute().
isInManualMode()
bool isInManualMode (void)
{
  return( manualModeFlagg);
}
References manualModeFlagg.
manualMode()
void manualMode (bool mode)
{
  manualModeFlagg= mode;
  ptr2timeHandler->bypass( mode);
}
References TimeHandler::bypass(), manualModeFlagg, and ptr2timeHandler.
Referenced by Controller::execute().
updateTime()
void updateTime (void)
{
  if( timer.isTimeout())
  {
    systemTimestamp++;
    ptr2timeHandler->updateTime( systemTimestamp);
  }
}
References Timer::isTimeout(), ptr2timeHandler, systemTimestamp, timer, and TimeHandler::updateTime().
Member Data Documentation
manualModeFlagg
bool manualModeFlagg private
Referenced by isInManualMode(), and manualMode().
ptr2timeHandler
TimeHandler* ptr2timeHandler private
Referenced by adjust(), manualMode(), and updateTime().
systemTimestamp
Timestamp systemTimestamp private
Referenced by adjust(), and updateTime().
timer
Timer timer private
Referenced by updateTime().
The documentation for this class was generated from the following files:
SystemTimeHandler.h
SystemTimeHandler.cpp