My Project: TM1638plus_common
TM1638plus_common
#include "TM1638plus_common.h"
Public Member Functions
TM1638plus_common ()
uint8_t HighFreqshiftin (uint8_t dataPin, uint8_t clockPin, uint8_t bitOrder)
void HighFreqshiftOut (uint8_t dataPin, uint8_t clockPin, uint8_t bitOrder, uint8_t val)
Detailed Description
Constructor & Destructor Documentation
TM1638plus_common()
TM1638plus_common ()
{
    // Blank constructor
}
Member Function Documentation
HighFreqshiftin()
uint8_t HighFreqshiftin (uint8_t dataPin, uint8_t clockPin, uint8_t bitOrder)
{
    uint8_t value = 0;
    uint8_t i = 0;
    for(i = 0; i < 8; ++i) {
        digitalWrite(clockPin, HIGH);
        delayMicroseconds(TM_HFIN_DELAY);
        if(bitOrder == LSBFIRST)
            value |= digitalRead(dataPin) << i;
        else
            value |= digitalRead(dataPin) << (7 - i);
        digitalWrite(clockPin, LOW);
        delayMicroseconds(TM_HFIN_DELAY);
    }
    return value;
}
References TM_HFIN_DELAY.
Referenced by TM1638plus::readButtons(), TM1638plus_Model2::ReadKey16(), and TM1638plus_Model2::ReadKey16Two().
HighFreqshiftOut()
void HighFreqshiftOut (uint8_t dataPin, uint8_t clockPin, uint8_t bitOrder, uint8_t val)
{
    uint8_t i;
    for (i = 0; i < 8; i++)  {
        if (bitOrder == LSBFIRST)
            digitalWrite(dataPin, !!(val & (1 << i)));
        else
            digitalWrite(dataPin, !!(val & (1 << (7 - i))));
        digitalWrite(clockPin, HIGH);
        delayMicroseconds(TM_HFOUT_DELAY);
        digitalWrite(clockPin, LOW);
        delayMicroseconds(TM_HFOUT_DELAY);
    }
}
References TM_HFOUT_DELAY.
Referenced by TM1638plus::sendData(), and TM1638plus_Model2::sendData().
The documentation for this class was generated from the following files:
extra/TM1638plus-master/TM1638plus-master/src/TM1638plus_common.h
extra/TM1638plus-master/TM1638plus-master/src/TM1638plus_common.cpp