My Project: OLEDDisplayClockViewHandler
OLEDDisplayClockViewHandler
#include "OLEDDisplayClockViewHandler.h"
Public Member Functions
OLEDDisplayClockViewHandler (TimeHandler *ptr)
virtual ~OLEDDisplayClockViewHandler (void)
virtual const char * getClassName (void)
virtual void updateTime (Timestamp &timestamp)
Public Member Functions inherited from TimeHandler
TimeHandler (TimeHandler *ptr=nullptr)
virtual ~TimeHandler (void)
virtual void bypass (bool bypassModule)
virtual const char * getClassName (void)=0
virtual bool isValidTime (void)
virtual void setValidTime (bool validFlagg)
virtual void updateTime (Timestamp &timestamp)
Private Member Functions
void doAction (void(*fun)(void))
Private Attributes
lcd_st7567s Lcd
Additional Inherited Members
Protected Attributes inherited from TimeHandler
bool bypassModule
TimeHandler * ptr
bool validTime
Detailed Description
Constructor & Destructor Documentation
OLEDDisplayClockViewHandler()
OLEDDisplayClockViewHandler (TimeHandler * ptr)
  :TimeHandler( ptr)
{
  Lcd.Init();
  Lcd.Clear(false);
};
References lcd_st7567s::Clear(), lcd_st7567s::Init(), and Lcd.
~OLEDDisplayClockViewHandler()
~OLEDDisplayClockViewHandler (void) virtual
{};
Member Function Documentation
doAction()
void doAction (void(*)(void) fun) private
{
  (*fun)();
}
getClassName()
const char * getClassName (void) virtual
Implements TimeHandler.
{
  return("OLEDDisplayClockViewHandler");
}
updateTime()
void updateTime (Timestamp & timestamp) virtual
Reimplemented from TimeHandler.
{
  const String dayOfWeekAsString[]={ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"};
  char dateStrBuffer[MyDate::getStringBufferSize()];
  std::string date= timestamp.getDate().toString( dateStrBuffer);
  char timeStrBuffer[MyDate::getStringBufferSize()];
  std::string time= timestamp.getTime().toString( timeStrBuffer);
  Lcd.Cursor(0, 0);                    //Character display position. y=0-3, x=0-17
  Lcd.Display((char*)"Current time:");
  Lcd.Cursor(0, 2);
  Lcd.Display((char*)dayOfWeekAsString[ ( timestamp.getDate()).getDayOfWeek()].c_str());               //Maximun 18 characters.
  Lcd.Cursor(0, 4);
  Lcd.Display((char*)date.c_str());               //Maximun 18 characters.
  Lcd.Cursor(0, 6);
  Lcd.Display((char*)time.c_str());               //Maximun 18 characters.
  TimeHandler::updateTime( timestamp);
}
References lcd_st7567s::Cursor(), lcd_st7567s::Display(), Timestamp::getDate(), MyDate::getStringBufferSize(), Timestamp::getTime(), Lcd, MyDate::toString(), MyTime::toString(), and TimeHandler::updateTime().
Member Data Documentation
Lcd
lcd_st7567s Lcd private
Referenced by OLEDDisplayClockViewHandler(), and updateTime().
The documentation for this class was generated from the following files:
OLEDDisplayClockViewHandler.h
OLEDDisplayClockViewHandler.cpp