My Project: NTPWiFiTimeHandler.cpp File Reference
NTPWiFiTimeHandler.cpp File Reference
#include "NTPWiFiTimeHandler.h"
Functions
static WiFiManagerParameter ntpserverparam ("server", "ntp server", "time.cloudflare.com", 40)
void onWifiConnect (const WiFiEventStationModeGotIP &event)
void onWifiDisconnect (const WiFiEventStationModeDisconnected &event)
Variables
static WiFiEventHandler wifiConnectHandler
static WiFiEventHandler wifiDisconnectHandler
static WiFiManager wm
Function Documentation
ntpserverparam()
static WiFiManagerParameter ntpserverparam ("server" , "ntp server" , "time.cloudflare.com" , 40) static
Referenced by NTPWiFiTimeHandler::init().
onWifiConnect()
void onWifiConnect (const WiFiEventStationModeGotIP & event)
{
  Serial.printf("Connected to Wi-Fi sucessfully to.... %s\n", wm.getWiFiSSID());
  Serial.print("IP address: ");  Serial.println( WiFi.localIP());
}
References wm.
Referenced by NTPWiFiTimeHandler::init().
onWifiDisconnect()
void onWifiDisconnect (const WiFiEventStationModeDisconnected & event)
{
  Serial.printf("Disconnected from Wi-Fi, trying to connect to.... %s\n", wm.getWiFiSSID());
  WiFi.disconnect();
  WiFi.begin( wm.getWiFiSSID(), wm.getWiFiPass());
}
References wm.
Referenced by NTPWiFiTimeHandler::init().
Variable Documentation
wifiConnectHandler
WiFiEventHandler wifiConnectHandler static
Referenced by NTPWiFiTimeHandler::init().
wifiDisconnectHandler
WiFiEventHandler wifiDisconnectHandler static
Referenced by NTPWiFiTimeHandler::init().
wm
WiFiManager wm static
Referenced by NTPWiFiTimeHandler::init(), onWifiConnect(), and onWifiDisconnect().