My Project: MyDate
MyDate
#include "MyDate.h"
Public Member Functions
MyDate (const MyDate &date)
MyDate (uint8_t day, uint8_t month, uint16_t year)
MyDate (void)
~MyDate (void)
void dayDec (void)
void dayInc (void)
uint8_t getDay (void) const
uint8_t getDayOfWeek (void) const
uint8_t getMonth (void) const
uint16_t getYear (void) const
void monthDec (void)
void monthInc (void)
MyDate & operator= (const MyDate &date)
void setDay (const uint8_t day)
void setMonth (const uint8_t month)
void setYear (const uint16_t year)
char * toString (char *buffer)
void yearDec (void)
void yearInc (void)
Static Public Member Functions
static MyDate getDSTEnd (uint16_t year)
static MyDate getDSTStart (uint16_t year)
static size_t getStringBufferSize (void)
static const char * getStringFormat (void)
static bool isValidDay (uint8_t day, uint8_t month, uint16_t year)
static bool isValidMonth (uint8_t month)
static bool isValidYear (uint16_t year)
Private Member Functions
uint8_t getCenturyCode (void) const
uint8_t getDayCode (void) const
uint8_t getLeapCode (void) const
uint8_t getMonthCode (void) const
uint8_t getYearCode (void) const
Private Attributes
uint8_t day
uint8_t month
uint16_t year
Detailed Description
Constructor & Destructor Documentation
MyDate() [1/3]
MyDate (void)
:day(BASE_DAY), month(BASE_MONTH), year(BASE_YEAR) {}
MyDate() [2/3]
MyDate (uint8_t day, uint8_t month, uint16_t year)
:day(day), month(month), year(year) {}
MyDate() [3/3]
MyDate (const MyDate & date)
:day(date.day), month(date.month), year(date.year) {}
~MyDate()
~MyDate (void)
{};
Member Function Documentation
dayDec()
void dayDec (void)
{
  day =( day> 1)? day-1:31;
}
References day.
Referenced by SystemTimeHandler::adjust().
dayInc()
void dayInc (void)
{
  day =( day< 31)? day+1:1;
}
References day.
Referenced by SystemTimeHandler::adjust().
getCenturyCode()
uint8_t getCenturyCode (void) const private
{   // Gegorian Calendar
    //                    1700  1800  1900  2000  2100  2200 2300
    uint8_t idx, code[]={    4,    2,    0,    6,    4,    2,   0};
    idx= (year/100) -17;
    return( code[ idx]);
}
References year.
Referenced by getDayOfWeek().
getDay()
uint8_t getDay (void) const
{
  return( day);
}
References day.
Referenced by Timestamp::setDate(), and TimeSunriseSunsetHandler::updateTime().
getDayCode()
uint8_t getDayCode (void) const inline private
{
    return( day);
}
References day.
Referenced by getDayOfWeek().
getDayOfWeek()
uint8_t getDayOfWeek (void) const
{
    //            #1 #2  #8            #3         #4                   #5                   #6
    uint8_t code= getYearCode()+ getDayCode()+ getMonthCode()- getLeapCode()+  getCenturyCode()-1;
    return( code %7);
}
References getCenturyCode(), getDayCode(), getLeapCode(), getMonthCode(), and getYearCode().
Referenced by getDSTEnd(), and getDSTStart().
getDSTEnd()
MyDate getDSTEnd (uint16_t year) static
{
    MyDate   date( 31, 10, year);
    uint8_t dayOfWeek=  date.getDayOfWeek();
    date.setDay( 31- dayOfWeek);
    return( date);
}
References getDayOfWeek(), setDay(), and year.
Referenced by TimeZoneDSTHandler::updateTime().
getDSTStart()
MyDate getDSTStart (uint16_t year) static
{
    MyDate   date( 31, 03, year);
    uint8_t dayOfWeek=  date.getDayOfWeek();
    date.setDay( 31- dayOfWeek);
    return( date);
}
References getDayOfWeek(), setDay(), and year.
Referenced by TimeZoneDSTHandler::updateTime().
getLeapCode()
uint8_t getLeapCode (void) const private
{
    uint8_t  result=0;
    if( IS_LEAP_YEAR( year) && ( month <3))
    {
        result= 1;
    }
    return( result);
}
References IS_LEAP_YEAR, month, and year.
Referenced by getDayOfWeek().
getMonth()
uint8_t getMonth (void) const
{
  return( month);
}
References month.
Referenced by Timestamp::setDate(), and TimeSunriseSunsetHandler::updateTime().
getMonthCode()
uint8_t getMonthCode (void) const private
{
  //                J  F  M    A  M  J    J  A  S    O  N  D
    uint8_t code[]= {1, 4, 4,   0, 2, 5,   0, 3, 6,   1, 4, 6};
    return( code[ month-1]);
}
References month.
Referenced by getDayOfWeek().
getStringBufferSize()
size_t getStringBufferSize (void) static
{
  return( strlen( MyDate::getStringFormat())+1);
}
References getStringFormat().
Referenced by Timestamp::toString(), OLEDDisplayClockViewHandler::updateTime(), and TimeZoneDSTHandler::updateTime().
getStringFormat()
const char * getStringFormat (void) static
{
  return( "%02d/%02d/%04d");
}
Referenced by getStringBufferSize(), Timestamp::getStringBufferSize(), and toString().
getYear()
uint16_t getYear (void) const
{
  return( year);
}
References year.
Referenced by Timestamp::setDate(), TimeSunriseSunsetHandler::updateTime(), and TimeZoneDSTHandler::updateTime().
getYearCode()
uint8_t getYearCode (void) const private
{
    uint16_t y= year% 100;
    return( (y + (y / 4)));
}
References year.
Referenced by getDayOfWeek().
isValidDay()
bool isValidDay (uint8_t day, uint8_t month, uint16_t year) static
{
   //                      1   2   3   4   5   6   7   8   9   10  11  12
   const uint8_t dofm[]={ 31, 28, 31, 30, 31, 30, 31, 31, 30,  31, 30, 31};
  return( day<= dofm[ month -1]+ ( IS_LEAP_YEAR( year)? 1:0));
}
References day, IS_LEAP_YEAR, month, and year.
isValidMonth()
bool isValidMonth (uint8_t month) static
{
  return( month <= 13);
}
References month.
isValidYear()
bool isValidYear (uint16_t year) static
{
  return( year >= 1970);
}
References year.
monthDec()
void monthDec (void)
{
  month =( month> 1)? month-1:12;
}
References month.
Referenced by SystemTimeHandler::adjust().
monthInc()
void monthInc (void)
{
  month =( month< 12)? month+1:1;
}
References month.
Referenced by SystemTimeHandler::adjust().
operator=()
MyDate & operator= (const MyDate & date)
{
    if( &date != this )
    {
        day=   date.day;
        month= date.month;
        year=  date.year;
    }
    return( *this);
}
References day, month, and year.
setDay()
void setDay (const uint8_t day)
{
   this->day= day;
}
References day.
Referenced by Timestamp::getDate(), getDSTEnd(), and getDSTStart().
setMonth()
void setMonth (const uint8_t month)
{
  this->month= month;
}
References month.
Referenced by Timestamp::getDate().
setYear()
void setYear (const uint16_t year)
{
  this->year= year;
}
References year.
Referenced by Timestamp::getDate().
toString()
char * toString (char * buffer)
{
  sprintf(buffer, MyDate::getStringFormat(), day, month, year);
  return( buffer);
}
References day, getStringFormat(), month, and year.
Referenced by Timestamp::toString(), OLEDDisplayClockViewHandler::updateTime(), and TimeZoneDSTHandler::updateTime().
yearDec()
void yearDec (void)
{
  year =( year> BASE_YEAR)? year-1:BASE_YEAR;
}
References BASE_YEAR, and year.
Referenced by SystemTimeHandler::adjust().
yearInc()
void yearInc (void)
{
  year =year+1;
}
References year.
Referenced by SystemTimeHandler::adjust().
Member Data Documentation
day
uint8_t day private
Referenced by dayDec(), dayInc(), getDay(), getDayCode(), isValidDay(), operator=(), setDay(), and toString().
month
uint8_t month private
Referenced by getLeapCode(), getMonth(), getMonthCode(), isValidDay(), isValidMonth(), monthDec(), monthInc(), operator=(), setMonth(), and toString().
year
uint16_t year private
Referenced by getCenturyCode(), getDSTEnd(), getDSTStart(), getLeapCode(), getYear(), getYearCode(), isValidDay(), isValidYear(), operator=(), setYear(), toString(), yearDec(), and yearInc().
The documentation for this class was generated from the following files:
MyDate.h
MyDate.cpp