My Project: SplitterTimeHandler
SplitterTimeHandler
#include "SplitterTimeHandler.h"
Public Member Functions
SplitterTimeHandler (TimeHandler *ptr, Timestamp &duplicatedTimestamp)
virtual ~SplitterTimeHandler (void)
virtual const char * getClassName (void)
virtual void updateTime (Timestamp &timestamp)
Public Member Functions inherited from TimeHandler
TimeHandler (TimeHandler *ptr=nullptr)
virtual ~TimeHandler (void)
virtual void bypass (bool bypassModule)
virtual const char * getClassName (void)=0
virtual bool isValidTime (void)
virtual void setValidTime (bool validFlagg)
virtual void updateTime (Timestamp &timestamp)
Protected Attributes
Timestamp & duplicatedTimestamp
Protected Attributes inherited from TimeHandler
bool bypassModule
TimeHandler * ptr
bool validTime
Detailed Description
Constructor & Destructor Documentation
SplitterTimeHandler()
SplitterTimeHandler (TimeHandler * ptr, Timestamp & duplicatedTimestamp)
  :duplicatedTimestamp( duplicatedTimestamp) {}
~SplitterTimeHandler()
~SplitterTimeHandler (void) virtual
{}
Member Function Documentation
getClassName()
const char * getClassName (void) virtual
Implements TimeHandler.
{
  return( "SplitterTimeHandler");
}
updateTime()
void updateTime (Timestamp & timestamp) virtual
Reimplemented from TimeHandler.
{
  duplicatedTimestamp.setEpochTime( timestamp.getEpochTime());
  TimeHandler::updateTime( timestamp);
}
References duplicatedTimestamp, Timestamp::getEpochTime(), Timestamp::setEpochTime(), and TimeHandler::updateTime().
Member Data Documentation
duplicatedTimestamp
Timestamp& duplicatedTimestamp protected
Referenced by updateTime().
The documentation for this class was generated from the following files:
SplitterTimeHandler.h
SplitterTimeHandler.cpp