My Project: TimeHandler
TimeHandler abstract
#include "TimeHandler.h"
Public Member Functions
TimeHandler (TimeHandler *ptr=nullptr)
virtual ~TimeHandler (void)
virtual void bypass (bool bypassModule)
virtual const char * getClassName (void)=0
virtual bool isValidTime (void)
virtual void setValidTime (bool validFlagg)
virtual void updateTime (Timestamp &timestamp)
Protected Attributes
bool bypassModule
TimeHandler * ptr
bool validTime
Private Member Functions
TimeHandler (const TimeHandler &)=delete
const TimeHandler & operator= (const TimeHandler &)=delete
Detailed Description
Constructor & Destructor Documentation
TimeHandler() [1/2]
TimeHandler (TimeHandler * ptr = nullptr)
:ptr(ptr) {}
~TimeHandler()
~TimeHandler (void) virtual
{}
TimeHandler() [2/2]
TimeHandler (const TimeHandler &) private delete
Member Function Documentation
bypass()
void bypass (bool bypassModule) virtual
{
  this->bypassModule= bypassModule;
  ptr->bypassModule=  bypassModule;
}
References bypassModule, and ptr.
Referenced by SystemTimeHandler::manualMode().
getClassName()
virtual const char * getClassName (void) pure virtual
Implemented in AnalogClockViewHandler, ConsoleViewHandler, LEDClockViewHandler, NTPWiFiTimeHandler, OLEDDisplayClockViewHandler, SplitterTimeHandler, TimeSunriseSunsetHandler, and TimeZoneDSTHandler.
isValidTime()
bool isValidTime (void) virtual
{
  if( ptr)
  {
    return( this->validTime);
  }
  return( false);
}
References ptr, and validTime.
Referenced by AnalogClockViewHandler::moveHands().
operator=()
const TimeHandler & operator= (const TimeHandler &) private delete
setValidTime()
void setValidTime (bool validFlagg) virtual
{
  this->validTime= validFlagg;
  if( ptr)
  {
//    Serial.printf("Class: %s\n", getClassName()),
    ptr->setValidTime( validFlagg);
  }
}
References ptr, setValidTime(), and validTime.
Referenced by setValidTime().
updateTime()
void updateTime (Timestamp & timestamp) virtual
Reimplemented in AnalogClockViewHandler, ConsoleViewHandler, LEDClockViewHandler, NTPWiFiTimeHandler, OLEDDisplayClockViewHandler, SplitterTimeHandler, TimeSunriseSunsetHandler, and TimeZoneDSTHandler.
{
  if( ptr)
  {
    ptr->updateTime( timestamp);
  }
}
References ptr, and updateTime().
Referenced by SystemTimeHandler::adjust(), AnalogClockViewHandler::updateTime(), ConsoleViewHandler::updateTime(), LEDClockViewHandler::updateTime(), NTPWiFiTimeHandler::updateTime(), OLEDDisplayClockViewHandler::updateTime(), SplitterTimeHandler::updateTime(), updateTime(), TimeSunriseSunsetHandler::updateTime(), TimeZoneDSTHandler::updateTime(), and SystemTimeHandler::updateTime().
Member Data Documentation
bypassModule
bool bypassModule protected
Referenced by bypass(), and NTPWiFiTimeHandler::updateTime().
ptr
TimeHandler* ptr protected
Referenced by bypass(), isValidTime(), setValidTime(), and updateTime().
validTime
bool validTime protected
Referenced by isValidTime(), and setValidTime().
The documentation for this class was generated from the following files:
TimeHandler.h
TimeHandler.cpp